_collection_groups:
- collections:
  - all_pages
  heading: Content Management
- collections:
  - services
  - service_categories
  - patient_pages
  - team_members
  heading: By Category
_inputs:
  description:
    type: textarea
  title:
    type: text
collections_config:
  all_pages:
    filter: strict
    glob:
    - '**/*.html'
    - '!_*/**'
    name: All Pages
    output: true
    parse_branch_index: true
    path: .
  patient_pages:
    name: Patient Pages
    output: true
    parse_branch_index: true
    path: for-patients
  service_categories:
    name: Service Categories
    output: true
    parse_branch_index: true
    path: service-categories
  services:
    name: Services
    output: true
    parse_branch_index: true
    path: services
  team_members:
    name: Team Members
    output: true
    parse_branch_index: true
    path: team-members
data_config:
  navigation:
    path: _data/navigation.yml
editor:
  default_editor_config:
    content:
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      link: true
      redo: true
      undo: true
  default_path: /
source: .
uploads:
  path: assets/images
